{
 "title": "K8s DPDK stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "DPDK telemetry stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DPDK Telemetry Bytes per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dpdk_telemetry_bytes_total{aggregate=\"0\"}[1m])) by (socket, pod, port, direction, type)"
    }
   ]
  },
  {
   "title": "DPDK Telemetry packets per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dpdk_telemetry_packets_total{aggregate=\"0\"}[1m])) by (socket, pod, port, direction, type)"
    }
   ]
  },
  {
   "title": "DPDK Telemetry errors per second (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dpdk_telemetry_errors_total{aggregate=\"0\"}[1m])) by (socket, pod, port, direction, type)"
    }
   ]
  },
  {
   "title": "DPDK Telemetry polls per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dpdk_telemetry_exporter_polls_total{aggregate=\"1\"}[1m])) by (socket, pod, type)"
    }
   ]
  },
  {
   "title": "DPDK Telemetry packet size 5m rate heatmap",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dpdk_telemetry_packets_size_bucket[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "DPDK Telemetry busy percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dpdk_telemetry_busy_percent{aggregate=\"1\"}) by (socket, pod, type)"
    }
   ]
  }
 ]
}